
language: csharp 
dotnet: 2.1.401
services:
  - mongodb
  
solution: ./mongodb-studies.sln
install:
    - dotnet restore ./mongodb-studies.sln

script: 
  - dotnet build Tests
  - dotnet test Tests
branches:
  only:
    - master