
language: csharp 
services:
  - mongodb
  
solution: ./mongodb-studies.sln
install:
    - nuget restore ./mongodb-studies.sln

script: 
  - bundle install 
  - rake test
branches:
  only:
    - master