version: 1.0.{build}
configuration: Release
image: Visual Studio 2022
services:
  - mongodb
before_build:
  - dotnet restore mongodb-studies.sln
build:
  project: mongodb-studies.sln
  verbosity: minimal
  publish_nuget: false
nuget:
  account_feed: false
  project_feed: false
  disable_publish_on_pr: true
branches:
  only:
    - master