version: 1.0.{build}
configuration: Release
before_build:
  - nuget restore mongodb-studies.sln
  - choco install mongodb
build:
  project: mongodb-studies.sln
  verbosity: minimal
  publish_nuget: false
nuget:
  account_feed: false
  project_feed: false
  disable_publish_on_pr: true
